--!native
--!optimize 2

--[[
	******************************************************************************
	* @file		  	: ...encodingTechiques.luau
	* @author	  	: scrpt2r
	* @date		  	: August 2026
	* @lastEdit		: August 08 2026 16:05
	* @brief	  	: A basic quaternion library.
	* @version		: 2.0.0
	******************************************************************************
	* @attention
	*
	* Copyright © 2026 Axon Corporation.
	* All rights reserved.
	*
	* This software is licensed under terms that can be found in the LICENSE file
	* in the root directory of this software component.
	* If no LICENSE file comes with this software, it is provided AS-IS.
	*
	******************************************************************************
--]]

--// Lib Decleration
local libs = script.libs
return require(libs.quaternion)
